FROM node:20 as build

WORKDIR /usr/petsitting

COPY package.json .

RUN npm install

COPY . ./

RUN npm run build

FROM nginx:alpine

COPY --from=build /usr/petsitting/dist /usr/share/nginx/html
RUN mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/df.conf
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]