version: "3.6"
services:
  pgDB:
    image: postgis/postgis:16-3.4
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: pet
volumes:
  db_data:
